name: Github Pages deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1
      with:
        version: '13.x'

    - name: Build
      run: |
        npm ci
        npm run build --modern

    - name: GitHub Pages deploy
      uses: peaceiris/actions-gh-pages@v3.5.6
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: master
          cname: mmkowalczyk.pl